
apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: my-app-cluster
  annotations:
    crossplane.io/external-name: my-app-cluster-dev  
spec:
  writeConnectionSecretToRef:
    name: my-app-cluster-dev-secret
  location: "North Europe"
  aks:
    adminUser: 82e3a65e-188d-4d79-a4f1-abdcf5fd1665
    tags:
      environment: dev
  virtualNetwork:
    tags:
      environment: dev   
